# Created with YamlCreate.ps1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: ktsu.BlastMerge
PackageVersion: 1.0.10
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- blastmerge
- BlastMerge.ConsoleApp
FileExtensions:
- txt
- md
- json
- yml
- yaml
- xml
- config
- cs
- js
- py
- java
- cpp
- c
- h
- hpp
ReleaseDate: 2025-05-31
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ktsu-dev/BlastMerge/releases/download/v1.0.10/BlastMerge.ConsoleApp-1.0.10-win-x64.zip
  InstallerSha256: F4DE5E3B19AB68638550A66102C1443C539AE3136420751116676AD9437AB7D2
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: BlastMerge.ConsoleApp.exe
    PortableCommandAlias: blastmerge
- Architecture: x86
  InstallerUrl: https://github.com/ktsu-dev/BlastMerge/releases/download/v1.0.10/BlastMerge.ConsoleApp-1.0.10-win-x86.zip
  InstallerSha256: 88593F5B6797DEE0ED3003699955E5ED87A06A48C6F033E37184C11FC2553223
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: BlastMerge.ConsoleApp.exe
    PortableCommandAlias: blastmerge
- Architecture: arm64
  InstallerUrl: https://github.com/ktsu-dev/BlastMerge/releases/download/v1.0.10/BlastMerge.ConsoleApp-1.0.10-win-arm64.zip
  InstallerSha256: 09D3242A89EB29FAD0BED7E084017E76EE6D29A3528260BED5280DA53BB9E5D2
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: BlastMerge.ConsoleApp.exe
    PortableCommandAlias: blastmerge
ManifestType: installer
ManifestVersion: 1.6.0
