# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: ktsu.BlastMerge
PackageVersion: 1.0.14
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- blastmerge
- BlastMerge.ConsoleApp
FileExtensions:
- txt
- md
- json
- yml
- yaml
- xml
- config
- cs
- js
- py
- java
- cpp
- c
- h
- hpp
ReleaseDate: 2025-06-02
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.9
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ktsu-dev/BlastMerge/releases/download/v1.0.14/BlastMerge.ConsoleApp-1.0.14-win-x64.zip
  InstallerSha256: FD083BA82BE20F09FBD0A97710EB3D3674DA023009FC4BDFBB022908B3DB3E2A
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ktsu.BlastMerge.ConsoleApp.exe
    PortableCommandAlias: blastmerge
- Architecture: x86
  InstallerUrl: https://github.com/ktsu-dev/BlastMerge/releases/download/v1.0.14/BlastMerge.ConsoleApp-1.0.14-win-x86.zip
  InstallerSha256: FB255A6696E847F9D3DB34FC49E820D4F3FCA27A50E34865C8520D925FDBF120
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ktsu.BlastMerge.ConsoleApp.exe
    PortableCommandAlias: blastmerge
- Architecture: arm64
  InstallerUrl: https://github.com/ktsu-dev/BlastMerge/releases/download/v1.0.14/BlastMerge.ConsoleApp-1.0.14-win-arm64.zip
  InstallerSha256: FE9A7044C8BEC1DE141B6948D91F75A6FE97947E4257F5067A6A947A7F2A3297
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ktsu.BlastMerge.ConsoleApp.exe
    PortableCommandAlias: blastmerge
ManifestType: installer
ManifestVersion: 1.10.0
